/** */
import React from "react";
import { Provider } from "react-redux";
import { act } from "react-dom/test-utils";
import { render, unmountComponentAtNode } from "react-dom";
import Store from "../../../store/_store";
import { Calendar } from "./index";

describe("<Calendar /> Suite", () => {
  let container = null,
    year = 2021,
    month = 8,
    onEditReminder = jest.fn(() => {});
  beforeEach(() => {
    container = document.createElement("div");
    document.body.appendChild(container);

    act(() => {
      render(
        <Provider store={Store}>
          <Calendar month={month} year={year} onEditReminder={onEditReminder} />
        </Provider>,
        container
      );
    });
  });

  afterEach(() => {
    unmountComponentAtNode(container);
    container.remove();
    container = null;
  });

  it("renders correctly:", () => {
    expect(container).toMatchInlineSnapshot(`
      <div>
        <main
          class="wrapper"
        >
          <div>
            <div
              class="heading"
            >
              <div>
                Sun
              </div>
              <div>
                Mon
              </div>
              <div>
                Tue
              </div>
              <div>
                Wed
              </div>
              <div>
                Thu
              </div>
              <div>
                Fri
              </div>
              <div>
                Sat
              </div>
            </div>
            <div
              class="content"
            >
              <div
                class="week"
              >
                <div
                  class="day"
                >
                  <h5>
                    1
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sun Aug 01 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    2
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Mon Aug 02 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    3
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Tue Aug 03 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    4
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Wed Aug 04 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    5
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Thu Aug 05 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    6
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Fri Aug 06 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    7
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sat Aug 07 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="week"
              >
                <div
                  class="day"
                >
                  <h5>
                    8
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sun Aug 08 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    9
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Mon Aug 09 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    10
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Tue Aug 10 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    11
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Wed Aug 11 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    12
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Thu Aug 12 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    13
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Fri Aug 13 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    14
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sat Aug 14 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="week"
              >
                <div
                  class="day"
                >
                  <h5>
                    15
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sun Aug 15 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    16
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Mon Aug 16 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    17
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Tue Aug 17 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    18
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Wed Aug 18 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    19
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Thu Aug 19 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    20
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Fri Aug 20 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    21
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sat Aug 21 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="week"
              >
                <div
                  class="day"
                >
                  <h5>
                    22
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sun Aug 22 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    23
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Mon Aug 23 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    24
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Tue Aug 24 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    25
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Wed Aug 25 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    26
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Thu Aug 26 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    27
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Fri Aug 27 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    28
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sat Aug 28 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="week"
              >
                <div
                  class="day"
                >
                  <h5>
                    29
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Sun Aug 29 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    30
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Mon Aug 30 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5>
                    31
                  </h5>
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Tue Aug 31 2021
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5 />
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Invalid Date
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5 />
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Invalid Date
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5 />
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Invalid Date
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="day"
                >
                  <h5 />
                  <div>
                    <div
                      class="modal"
                    >
                      <div
                        class="modalBody"
                      >
                        <div
                          class="modalHeader"
                        >
                          <div
                            class="modalTitle"
                          >
                             
                            <h5>
                              Invalid Date
                            </h5>
                          </div>
                          <div
                            class="closeIcon is-clickable"
                          >
                            ×
                          </div>
                        </div>
                        <div
                          class="modalContent"
                        >
                          <div
                            class="list"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    `);
  });
});
